### ISSUE TITLE
bug zoom and unzoom

### ISSUE THREAD

**Issue by appt2** [GetStream/photoview-android#1]
Display Metrics:
- Width: 1080px
- Height: 2176px
- Density: 440dpi
- Scaled Density: 2.75

Build Information:
- Board: moonstone
- Brand: POCO
- Device ID: UKQ1.231003.002
- Display: UKQ1.231003.002 release-keys
- Manufacturer: Xiaomi
- Model: 22111317PG
- Product: moonstone_p_global
- Serial Number: unknown

Telephony Information:
- Sim Operator Name: Irancell
- Phone Type: GSM
SDK: 34
Android: 14
Model: V816.0.3.0.UMPMIXM
App version: 1.5.6

java.lang.IllegalArgumentException: invalid pointerIndex -1 for MotionEvent { action=MOVE, id[0]=1, x[0]=347.518, y[0]=1536.73, historySize=2, eventTime=370454876252569, downTime=370454566641000, deviceId=3, source=TOUCHSCREEN, displayId=0, eventId=853530290}
	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getX(MotionEvent.java:2677)
	at androidx.viewpager.widget.ViewPager.onInterceptTouchEvent(ViewPager.java:2072)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2674)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:577)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1908)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4584)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:535)
	at android.view.View.dispatchPointerEvent(View.java:16154)
	at com.xiaomi.mirror.MiuiMirrorImpl.isHandled(MiuiMirrorImpl.java:152)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7875)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7641)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7013)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7070)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7036)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7201)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7044)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7258)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7017)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7070)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7036)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7044)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7017)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10187)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10138)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10102)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10350)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:307)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:275)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:10275)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:10444)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1626)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1635)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1170)
	at android.view.Choreographer.doFrame(Choreographer.java:1067)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1599)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

Thu Feb 15 17:58:08 GMT+03:30 2024

**Comment by cbeyls** [comment]
See known issue and workaround in the original implementation:
https://github.com/Baseflow/PhotoView?tab=readme-ov-file#issues-with-viewgroups

**Comment by skydoves** [comment]
Check out this implementation: https://github.com/GetStream/photoview-android/blob/main/sample/src/main/kotlin/io/getstream/photoview/sample/HackyViewPager.kt
