### ISSUE TITLE
Error when using scaleType to display an image from the drawable folder

### ISSUE THREAD

**Issue by ArleyPereira** [GetStream/photoview-android#2]
- Library Version [1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy A52s 5G with Android 14]
 
**Describe the Bug:**

Error when using scaleType to display an image from the drawable folder

**Expected Behavior:**

Display an image from the drawable folder

`FATAL EXCEPTION: main
Process: br.com.hellodev.photoview, PID: 21326
java.lang.RuntimeException: Unable to start activity ComponentInfo{br.com.hellodev.photoview/br.com.hellodev.photoview.MainActivity}: android.view.InflateException: Binary XML file line #18 in br.com.hellodev.photoview:layout/activity_main: Binary XML file line #18 in br.com.hellodev.photoview:layout/activity_main: Error inflating class io.getstream.photoview.PhotoView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: android.view.InflateException: Binary XML file line #18 in br.com.hellodev.photoview:layout/activity_main: Binary XML file line #18 in br.com.hellodev.photoview:layout/activity_main: Error inflating class io.getstream.photoview.PhotoView
Caused by: android.view.InflateException: Binary XML file line #18 in br.com.hellodev.photoview:layout/activity_main: Error inflating class io.getstream.photoview.PhotoView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:882)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1034)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:989)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1151)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1112)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:700)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:491)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
	at br.com.hellodev.photoview.MainActivity.onCreate(MainActivity.kt:10)
	at android.app.Activity.performCreate(Activity.java:8944)
	at android.app.Activity.performCreate(Activity.java:8913)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property attacher has not been initialized
	at io.getstream.photoview.PhotoView.setScaleType(PhotoView.kt:82)
	at android.widget.ImageView.<init>(ImageView.java:219)
	at android.widget.ImageView.<init>(ImageView.java:191)
	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:78)
	at io.getstream.photoview.PhotoView.<init>(PhotoView.kt:38)
	at io.getstream.photoview.PhotoView.<init>(PhotoView.kt:34)
	at io.getstream.photoview.PhotoView.<init>(Unknown Source:11)
	... 29 more`

![Screenshot at Feb 17 14-32-14](https://github.com/GetStream/photoview-android/assets/47366406/6a29d8c1-b2b8-41c0-8e47-59164c6dc0ce)
![Screenshot at Feb 17 14-32-28](https://github.com/GetStream/photoview-android/assets/47366406/5325dd63-1c8f-4320-aeb2-0575849fa3c8)
![Screenshot at Feb 17 14-35-12](https://github.com/GetStream/photoview-android/assets/47366406/efc063ec-0a02-49d1-91a2-ab38f5e587e5)

**Comment by skydoves** [comment]
Hey @ArleyPereira, thanks for reporting this issue. It will be fixed in the next release.

**Comment by skydoves** [comment]
It has been fixed in the new release, version 1.0.1. Thanks for reporting this issue!
